#  原本 deepseek chat api 的配置
#spring:
#  ai:
#    openai:
#      # DeepSeek API Key
#      api-key: ${SPRING_AI_DEEPSEEK_API_KEY}
#      base-url: https://api.deepseek.com
#      chat:
#        options:
#          # DeepSeek 模型名称 (deepseek-chat 和 deepseek-reasoner)
#          model: deepseek-chat
#          temperature: 0.5

#langchain4j:
#  open-ai:
#    chat-model:
#      base-url: https://api.deepseek.com
#      api-key: ${SPRING_AI_DEEPSEEK_API_KEY}  # 换成你的 Key
#      model-name: deepseek-chat
#      temperature: 0.2  # 这种任务建议温度低一点，更稳定
#      log-requests: true
#      log-responses: true

# 阿里百炼平台示例
#spring:
#  ai:
#    openai:
#      # API Key
#      api-key: ${ALIBABA_API_KEY}
#      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
#      chat:
#        options:
#          model: qwen3-coder-plus
#          temperature: 0.5


spring:
  ai:
    openai:
      # API Key
      api-key: ${SPRING_AI_DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-v4-pro
          temperature: 0.5

server:
  port: 8080
